/**
 * 取引完了伝票
 */
export interface completionSlip {
  // 伝票番号
  slipNo: string;
  // 伝票管理ユーザーID
  slipAdminUserId: string;
  // 伝票管理ユーザー名
  slipAdminUserName: string;
  // 伝票管理工場ID
  slipAdminOfficeId: string;
  // 伝票管理工場名
  slipAdminOfficeName: string;
  // 伝票管理メカニックID
  slipAdminMechanicId: string;
  // 伝票管理メカニック名
  slipAdminMechanicName: string;
  // 管理者区分
  adminDiv: string;
  // タイトル
  title: string;
  // 価格
  praice: string;
  // 説明
  explanation: string;
  // 入札者ID
  bidderId: string;
  // 入札完了日
  bidEndDate: string;
  // 対象サービス内容
  targetService: string;
  // 対象車両ID
  targetVehicleId: string;
  // 対象車両名
  targetVehicleName: string;
  // 作業場所情報
  workAreaInfo: string;
  // 評価ID
  evaluationId: string;
  // 完了日付
  completionDate: string;
  // 取引完了日
  transactionCompletionDate: string;
  // 画像urlリスト
  imageUrlList: string[]| null;
  // 作成日時
  created: string;
  // 更新日時
  updated: string;
}

export const initCompletionSlip: completionSlip = {
   // 伝票番号
   slipNo: '0',
   // 伝票管理ユーザーID
   slipAdminUserId: '0',
   // 伝票管理ユーザー名
   slipAdminUserName: '',
   // 伝票管理工場ID
   slipAdminOfficeId: '0',
   // 伝票管理工場名
   slipAdminOfficeName: '',
   // 伝票管理メカニックID
   slipAdminMechanicId: '0',
   // 伝票管理メカニック名
   slipAdminMechanicName: '',
   // 管理者区分
   adminDiv: '0',
   // タイトル
   title: '',
   // 価格
   praice: '',
   // 説明
   explanation: '',
   // 入札者ID
   bidderId: '0',
   // 入札完了日
   bidEndDate: '0',
   // 対象サービス内容
   targetService: '0',
   // 対象車両ID
   targetVehicleId: '0',
   // 対象車両名
   targetVehicleName: '',
   // 作業場所情報
   workAreaInfo: '0',
   // 評価ID
   evaluationId: '0',
   // 完了日付
   completionDate: '0',
   // 取引完了日
   transactionCompletionDate: '0',
   // 画像urlリスト
   imageUrlList: null,
   // 作成日時
   created: '0',
   // 更新日時
   updated: '0',
}
