export const mylistMessages = {
  // 運営メッセ―ジ
  OPR_MSG: '運営メッセージ',
  // 質問中
  QUESTIONING: '質問中',
  // 質問あり（未回答）
  UN_QUESTIONING: '質問あり（未回答）',
  // 回答済
  TO_ANSWERED: '回答済',
  // 回答あり
  FR_ANSWERED: '回答あり',
  // メッセージのFrom
  FROM_MSG: 'メッセージのFrom',
  // メッセージのTo
  TO_MSG: 'メッセージのTo',
  // 管理伝票への入札（取引依頼）があった場合
  TRAN_RES: '取引依頼がきてます。',
  // 管理伝票への見積もりが作成された場合
  ESTIMATE_RES: '見積あり',
  // 出品中
  EXHIBITING: '出品中',
  // 取引開始（管理者）
  TRAN_ST: '取引開始',
  // 希望日超え、取引なし
  EXPIRED: '希望日が過ぎています。取引依頼はありませんでした。',
  // 管理伝票取消
  ADMIN_CANCEL: '伝票取消',
  // 取引依頼中（依頼者が管理者に）
  TRAN_REQ: '取引依頼中',
  // 見積提示・取引依頼中（依頼者が管理者に）
  ESTIMATE_REQ: '見積提示・取引依頼中',
  // 取引開始（依頼者）
  TRAN_START: '取引開始',
  // 他の方との取引が決定しました。
  UNSUCCESSFUL: '他の方との取引が決定しました。',
  // 取引完了
  TRAN_COMP: '取引完了',
  // 完了予定日の場合
  COMP_DATE: '完了予定日をとなってます。',
  // 完了予定日が設定。
  COMP_DATE_SET: '完了予定日が設定されました。',
  // 完了予定日が変更。
  COMP_DATE_CHANGE: '完了予定日が変更されました。',
  // 評価依頼。
  EVALUATION_REQ: '評価をおこなってください。',
  // 再出品。
  RELISTED_SERVICE: '再出品しました。'  
} as const;